services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n-mcp-demo
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=${N8N_HOST:-localhost}
      - N8N_PORT=5678
      - N8N_PROTOCOL=${N8N_PROTOCOL:-http}
      - NODE_ENV=production
      - WEBHOOK_URL=${WEBHOOK_URL:-http://localhost:5678/}
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE:-America/New_York}
      # MCP Configuration
      - MCP_SERVER_URL=${MCP_SERVER_URL:-http://mcp-server:8080}
      - MCP_API_KEY=${MCP_API_KEY:-demo-key-change-in-production}
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - n8n-mcp-network
    depends_on:
      - mcp-server

  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile.mcp
    image: mcp-server:latest
    container_name: mcp-server-demo
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - n8n-mcp-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  n8n_data:
    driver: local

networks:
  n8n-mcp-network:
    driver: bridge
